[project]
name = "learn-google-adk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "google-adk>=0.2.0",
    "litellm>=1.67.0.post1",
    "mcp>=1.6.0",
]
